version: "3.2"
services:
  documentservice:
    build: documentService
    image: moonblade/documentservice
    ports:
      - "3002:3002"
  statusservice:
    build: statusService
    image: moonblade/statusservice
    ports:
      - "3003:3003"
    volumes:
      - ~/.config/gcloud:/home/.config/gcloud
    environment:
      GCLOUD_PROJECT: "plucky-door-200208"
      GOOGLE_APPLICATION_CREDENTIALS: "/home/.config/gcloud/gcloud.json"
  userinterface:
    build: userInterface
    image: moonblade/userinterface
    ports:
      - "3001:3001"
    volumes:
      - ~/.config/gcloud:/home/.config/gcloud
    environment:
      GCLOUD_PROJECT: "plucky-door-200208"
      GOOGLE_APPLICATION_CREDENTIALS: "/home/.config/gcloud/gcloud.json"
  watermarker:
    build: watermarker
    image: moonblade/watermarker
    ports:
      - "3000:3000"
    volumes:
      - ~/.config/gcloud:/home/.config/gcloud
    environment:
      GCLOUD_PROJECT: "plucky-door-200208"
      GOOGLE_APPLICATION_CREDENTIALS: "/home/.config/gcloud/gcloud.json"
  worker:
    build: worker
    image: moonblade/worker
    volumes:
      - ~/.config/gcloud:/home/.config/gcloud
    environment:
      GCLOUD_PROJECT: "plucky-door-200208"
      GOOGLE_APPLICATION_CREDENTIALS: "/home/.config/gcloud/gcloud.json"
